### ISSUE TITLE
Syntax error when parsing schemas with types that implement multiple interfaces

### ISSUE THREAD

**Issue by nicodn** [EasyGraphQL/easygraphql-parser#15]
The following schema fails to parse:
```
interface Node {
  id: ID!
}

interface Object {
  name: String!
  id: ID!
}

type ActualThing implements Object, Node {
  name: String!
  id: ID!
  property: Int!
}
```

Error:
```
Syntax Error: Unexpected Name "Node"

GraphQL request (10:37)
 9: 
10: type ActualThing implements Object, Node {
                                        ^
11:   name: String!

    at syntaxError (node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (node_modules/graphql/language/parser.js:1491:33)
    at parseDefinition (node_modules/graphql/language/parser.js:155:9)
    at many (node_modules/graphql/language/parser.js:1524:16)
    at parseDocument (node_modules/graphql/language/parser.js:115:18)
    at parse (node_modules/graphql/language/parser.js:50:10)
    at schemaParser (node_modules/easygraphql-parser/lib/schemaParser.js:208:24)
```

**Comment by nicodn** [comment]
Found a workaround using `{ allowLegacySDLImplementsInterfaces: true }`

https://github.com/graphql/graphql-js/pull/1169

**Comment by estrada9166** [comment]
@nicodn There is a new version on npm `v0.0.9`🎉

Thanks for creating the issue and also the PR!
